### ISSUE TITLE
Quotelist htmlpage: regular users can't change page

### ISSUE THREAD

**Issue by Parnassius** [Parnassius/cerbottana#184]

**Comment by palt0** [comment]
Commands with `parametrize_room=True` still check whether an user has relevant auth in `msg.parametrized_room` to ensure that `required_rank` is respected. This is an intended behaviour for elevated permissions, but the check could be skipped at voice level.
In other words, _is it fair to assume that if a command is broadcastable in a room at voice level, then it can also be accessible in PM to any regular users that are in such room, without any harm?_
Currently it's not a valid assumption because some parametrized commands temporarily rely on the old logic as a safety measure (`addquote`/`removequote`). People are actively using those at voice level in private rooms, so we can't just revert that, but we could set `parametrize_room` back to `False` for them.
In general the problematic commands are those that produce an effect on the target room (i.e. adding a quote) instead of just writing an output related to it.
A valid concern is that if in the future we allow changing permission levels dynamically (see #103), end users might lower permissions of spammable commands.

The current issue is obviously a side effect of this logic because changing page triggers a `.quotelist` command that requires voice permissions.
I'll update the logic but let me know what you think.
